# Generated by Django 3.2.8 on 2021-10-24 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciukune_mailing', '0002_rename_mailaddress_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail', to=settings.AUTH_USER_MODEL),
        ),
    ]
